import Head from 'next/head'
import s from '../styles/Home.module.scss'

const Home = () => {

  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main} data-testid="home">
        <h1 className={s.title}>
          Yet <a target="_blank" rel="noreferrer" href="https://heliotrope-wish-112.notion.site/Matt-Collier-portfolio-26f03cfc72b546eab77a095d9f98d7d3">another</a> unfinished project
        </h1>
      </main>
    </div>
  )
}

export default Home
