import Head from 'next/head'
import s from '../styles/Home.module.scss'
import { useMultistepForm } from "../hooks/useMultistepForm.ts"

const Home = () => {

  const { step, steps, currentStepIndex, isFirstStep, back, next } = useMultistepForm([<div>One</div>, <div>Two</div>])

  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main} data-testid="home">
        <div className={s.form}>
          <h3 className={s.h3}>hello world</h3> 
          <form>
            <div style={{ position: "absolute", top: "0.5rem", right: "0.5rem"  }}>{currentStepIndex + 1} / {steps.length}</div>
            {step}
            <div className={s.buttons}> 
              {!isFirstStep && <button type="button" onClick={back}>Previous</button> }
              {isFirstStep &&  <button type="button" onClick={next}>Next</button>}
              
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}

export default Home
